"""init completo

Revision ID: 13c724556365
Revises: 
Create Date: 2025-05-23 13:52:37.647020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c724556365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politica_cancelacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('penalizacion_dias', sa.Integer(), nullable=True),
    sa.Column('porcentaje_penalizacion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('localidad', sa.Text(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('dni', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contrasena', sa.String(length=255), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('es_empleado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_empleado', sa.String(length=255), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('modelo', sa.String(length=255), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('precio_dia', sa.Float(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('politica_cancelacion_id', sa.Integer(), nullable=True),
    sa.Column('estado_vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_vehiculo'], ['estado_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['politica_cancelacion_id'], ['politica_cancelacion.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado_reserva', sa.Integer(), nullable=True),
    sa.Column('pagada', sa.Boolean(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estado_reserva'], ['estado_reserva.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva_extra',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('extra_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.PrimaryKeyConstraint('reserva_id', 'extra_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_extra')
    op.drop_table('reserva')
    op.drop_table('vehiculo')
    op.drop_table('empleado')
    op.drop_table('administrador')
    op.drop_table('usuario')
    op.drop_table('sucursal')
    op.drop_table('politica_cancelacion')
    op.drop_table('extras')
    op.drop_table('estado_vehiculo')
    op.drop_table('estado_reserva')
    # ### end Alembic commands ###
